openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-alicloud-kvstore-redis
components:
  schemas:
    variables:
      required:
      - infrastructure
      type: object
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.

            Examples:
            ```
            context:
              project:
                name: string
                id: string
              environment:
                name: string
                id: string
              resource:
                name: string
                id: string
            ```
          default: {}
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.

            Examples:
            ```
            infrastructure:
              vpc_id: string                  # the ID of the VPC where the redis service applies
              kms_key_id: sting,optional      # the ID of the KMS key which to encrypt the redis data
              domain_suffix: string           # a private DNS namespace of the CloudMap where to register the applied redis service
            ```
          required:
          - domain_suffix
          - vpc_id
          properties:
            domain_suffix:
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 3
            kms_key_id:
              title: Kms Key Id
              type: string
              x-walrus-ui:
                order: 2
            vpc_id:
              title: Vpc Id
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          enum:
          - 1
          - 3
          - 5
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version.
          default: "5.0"
          enum:
          - "5.0"
          - "4.0"
          x-walrus-ui:
            group: Basic
            order: 5
        engine_parameters:
          title: Engine Parameters
          type: array
          description: |
            Specify the deployment parameters, see https://www.alibabacloud.com/help/zh/redis/user-guide/supported-parameters#concept-2087327.
          default: []
          items:
            properties:
              name:
                title: Name
                type: string
              value:
                title: Value
                type: string
            required:
            - name
            - value
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
            hidden: true
        password:
          title: Password
          type: string
          description: |
            Specify the account password.
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 7
